<?php

namespace Proxies\__CG__\JdrCorp\GuildesBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Machination extends \JdrCorp\GuildesBundle\Entity\Machination implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setNiveau($niveau)
    {
        $this->__load();
        return parent::setNiveau($niveau);
    }

    public function getNiveau()
    {
        $this->__load();
        return parent::getNiveau();
    }

    public function setNovice($novice)
    {
        $this->__load();
        return parent::setNovice($novice);
    }

    public function getNovice()
    {
        $this->__load();
        return parent::getNovice();
    }

    public function setinitie($initie)
    {
        $this->__load();
        return parent::setinitie($initie);
    }

    public function getInitie()
    {
        $this->__load();
        return parent::getInitie();
    }

    public function setExpert($expert)
    {
        $this->__load();
        return parent::setExpert($expert);
    }

    public function getExpert()
    {
        $this->__load();
        return parent::getExpert();
    }

    public function setEffetPervers($effetPervers)
    {
        $this->__load();
        return parent::setEffetPervers($effetPervers);
    }

    public function getEffetPervers()
    {
        $this->__load();
        return parent::getEffetPervers();
    }

    public function setChapitre(\JdrCorp\GuildesBundle\Entity\Chapitre $chapitre)
    {
        $this->__load();
        return parent::setChapitre($chapitre);
    }

    public function getChapitre()
    {
        $this->__load();
        return parent::getChapitre();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nom', 'niveau', 'description', 'novice', 'initie', 'expert', 'effetPervers', 'chapitre');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}