<?php

namespace Proxies\__CG__\JdrCorp\GuildesBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Competence extends \JdrCorp\GuildesBundle\Entity\Competence implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setChapitre(\JdrCorp\GuildesBundle\Entity\Chapitre $chapitre)
    {
        $this->__load();
        return parent::setChapitre($chapitre);
    }

    public function getChapitre()
    {
        $this->__load();
        return parent::getChapitre();
    }

    public function setCarac(\JdrCorp\GuildesBundle\Entity\Carac $carac)
    {
        $this->__load();
        return parent::setCarac($carac);
    }

    public function getCarac()
    {
        $this->__load();
        return parent::getCarac();
    }

    public function setApprenti($apprenti)
    {
        $this->__load();
        return parent::setApprenti($apprenti);
    }

    public function getApprenti()
    {
        $this->__load();
        return parent::getApprenti();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nom', 'apprenti', 'chapitre', 'carac');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}