<?php

namespace Proxies\__CG__\JdrCorp\ElricBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Perso extends \JdrCorp\ElricBundle\Entity\Perso implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setProprio($proprio)
    {
        $this->__load();
        return parent::setProprio($proprio);
    }

    public function getProprio()
    {
        $this->__load();
        return parent::getProprio();
    }

    public function setFort($fort)
    {
        $this->__load();
        return parent::setFort($fort);
    }

    public function getFort()
    {
        $this->__load();
        return parent::getFort();
    }

    public function setConsti($consti)
    {
        $this->__load();
        return parent::setConsti($consti);
    }

    public function getConsti()
    {
        $this->__load();
        return parent::getConsti();
    }

    public function setTaille($taille)
    {
        $this->__load();
        return parent::setTaille($taille);
    }

    public function setModifDegats()
    {
        $this->__load();
        return parent::setModifDegats();
    }

    public function getModifDegats()
    {
        $this->__load();
        return parent::getModifDegats();
    }

    public function getTaille()
    {
        $this->__load();
        return parent::getTaille();
    }

    public function setIntell($intell)
    {
        $this->__load();
        return parent::setIntell($intell);
    }

    public function getIntell()
    {
        $this->__load();
        return parent::getIntell();
    }

    public function setPouvoir($pouvoir)
    {
        $this->__load();
        return parent::setPouvoir($pouvoir);
    }

    public function getPouvoir()
    {
        $this->__load();
        return parent::getPouvoir();
    }

    public function setDexte($dexte)
    {
        $this->__load();
        return parent::setDexte($dexte);
    }

    public function getDexte()
    {
        $this->__load();
        return parent::getDexte();
    }

    public function setApparence($apparence)
    {
        $this->__load();
        return parent::setApparence($apparence);
    }

    public function getApparence()
    {
        $this->__load();
        return parent::getApparence();
    }

    public function setNaiss($naiss)
    {
        $this->__load();
        return parent::setNaiss($naiss);
    }

    public function getNaiss()
    {
        $this->__load();
        return parent::getNaiss();
    }

    public function setSexe($sexe)
    {
        $this->__load();
        return parent::setSexe($sexe);
    }

    public function getSexe()
    {
        $this->__load();
        return parent::getSexe();
    }

    public function setAge($age)
    {
        $this->__load();
        return parent::setAge($age);
    }

    public function getAge()
    {
        $this->__load();
        return parent::getAge();
    }

    public function setAllure($allure)
    {
        $this->__load();
        return parent::setAllure($allure);
    }

    public function getAllure()
    {
        $this->__load();
        return parent::getAllure();
    }

    public function setCompetences($comp)
    {
        $this->__load();
        return parent::setCompetences($comp);
    }

    public function getCompetences()
    {
        $this->__load();
        return parent::getCompetences();
    }

    public function setSorts($sorts)
    {
        $this->__load();
        return parent::setSorts($sorts);
    }

    public function getSorts()
    {
        $this->__load();
        return parent::getSorts();
    }

    public function setMetier($metier_id)
    {
        $this->__load();
        return parent::setMetier($metier_id);
    }

    public function getMetier()
    {
        $this->__load();
        return parent::getMetier();
    }

    public function setArmes($armes)
    {
        $this->__load();
        return parent::setArmes($armes);
    }

    public function getArmes()
    {
        $this->__load();
        return parent::getArmes();
    }

    public function setArmure($armure)
    {
        $this->__load();
        return parent::setArmure($armure);
    }

    public function getArmure()
    {
        $this->__load();
        return parent::getArmure();
    }

    public function getIdee()
    {
        $this->__load();
        return parent::getIdee();
    }

    public function getChance()
    {
        $this->__load();
        return parent::getChance();
    }

    public function getDexterite()
    {
        $this->__load();
        return parent::getDexterite();
    }

    public function getCharisme()
    {
        $this->__load();
        return parent::getCharisme();
    }

    public function getPv()
    {
        $this->__load();
        return parent::getPv();
    }

    public function getMana()
    {
        $this->__load();
        return parent::getMana();
    }

    public function setIdee()
    {
        $this->__load();
        return parent::setIdee();
    }

    public function setChance()
    {
        $this->__load();
        return parent::setChance();
    }

    public function setDexterite()
    {
        $this->__load();
        return parent::setDexterite();
    }

    public function setCharisme()
    {
        $this->__load();
        return parent::setCharisme();
    }

    public function setPv()
    {
        $this->__load();
        return parent::setPv();
    }

    public function setMana()
    {
        $this->__load();
        return parent::setMana();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nom', 'proprio', 'fort', 'consti', 'taille', 'intell', 'pouvoir', 'dexte', 'apparence', 'naiss', 'sexe', 'age', 'allure', 'competences', 'sorts', 'metier', 'armes', 'armure', 'idee', 'chance', 'dexterite', 'charisme', 'modif_degats', 'pv', 'mana');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}