<?php

namespace Proxies\__CG__\JdrCorp\GuildesBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CDBMaison extends \JdrCorp\GuildesBundle\Entity\CDBMaison implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setMaison(\JdrCorp\GuildesBundle\Entity\Maison $maison)
    {
        $this->__load();
        return parent::setMaison($maison);
    }

    public function getMaison()
    {
        $this->__load();
        return parent::getMaison();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTitre($titre)
    {
        $this->__load();
        return parent::setTitre($titre);
    }

    public function getTitre()
    {
        $this->__load();
        return parent::getTitre();
    }

    public function setCdb($cdb)
    {
        $this->__load();
        return parent::setCdb($cdb);
    }

    public function getCdb()
    {
        $this->__load();
        return parent::getCdb();
    }

    public function setEffet($effet)
    {
        $this->__load();
        return parent::setEffet($effet);
    }

    public function getEffet()
    {
        $this->__load();
        return parent::getEffet();
    }

    public function setMes($mes)
    {
        $this->__load();
        return parent::setMes($mes);
    }

    public function getMes()
    {
        $this->__load();
        return parent::getMes();
    }

    public function setMesEffet($mesEffet)
    {
        $this->__load();
        return parent::setMesEffet($mesEffet);
    }

    public function getMesEffet()
    {
        $this->__load();
        return parent::getMesEffet();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'titre', 'cdb', 'effet', 'mes', 'mesEffet', 'maison');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}