<?php

namespace Proxies\__CG__\JdrCorp\ElricBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Arme extends \JdrCorp\ElricBundle\Entity\Arme implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setBase($base)
    {
        $this->__load();
        return parent::setBase($base);
    }

    public function getBase()
    {
        $this->__load();
        return parent::getBase();
    }

    public function setDegats($degats)
    {
        $this->__load();
        return parent::setDegats($degats);
    }

    public function getDegats()
    {
        $this->__load();
        return parent::getDegats();
    }

    public function setMains($mains)
    {
        $this->__load();
        return parent::setMains($mains);
    }

    public function getMains()
    {
        $this->__load();
        return parent::getMains();
    }

    public function setStructure($structure)
    {
        $this->__load();
        return parent::setStructure($structure);
    }

    public function getStructure()
    {
        $this->__load();
        return parent::getStructure();
    }

    public function setForDex($for_dex)
    {
        $this->__load();
        return parent::setForDex($for_dex);
    }

    public function getForDex()
    {
        $this->__load();
        return parent::getForDex();
    }

    public function setType($type)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function setPrix($prix)
    {
        $this->__load();
        return parent::setPrix($prix);
    }

    public function getPrix()
    {
        $this->__load();
        return parent::getPrix();
    }

    public function setTotal($total)
    {
        $this->__load();
        return parent::setTotal($total);
    }

    public function getTotal()
    {
        $this->__load();
        return parent::getTotal();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nom', 'base', 'degats', 'mains', 'structure', 'for_dex', 'type', 'prix', 'total');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}