<?php

namespace Proxies\__CG__\JdrCorp\GuildesBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Tour extends \JdrCorp\GuildesBundle\Entity\Tour implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setPortee($portee)
    {
        $this->__load();
        return parent::setPortee($portee);
    }

    public function getPortee()
    {
        $this->__load();
        return parent::getPortee();
    }

    public function setCible($cible)
    {
        $this->__load();
        return parent::setCible($cible);
    }

    public function getCible()
    {
        $this->__load();
        return parent::getCible();
    }

    public function setDuree($duree)
    {
        $this->__load();
        return parent::setDuree($duree);
    }

    public function getDuree()
    {
        $this->__load();
        return parent::getDuree();
    }

    public function setEffet($effet)
    {
        $this->__load();
        return parent::setEffet($effet);
    }

    public function getEffet()
    {
        $this->__load();
        return parent::getEffet();
    }

    public function setMaison(\JdrCorp\GuildesBundle\Entity\Maison $maison)
    {
        $this->__load();
        return parent::setMaison($maison);
    }

    public function getMaison()
    {
        $this->__load();
        return parent::getMaison();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nom', 'portee', 'cible', 'duree', 'effet', 'maison');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}