<?php

namespace Proxies\__CG__\JdrCorp\GuildesBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Armure extends \JdrCorp\GuildesBundle\Entity\Armure implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setInit($init)
    {
        $this->__load();
        return parent::setInit($init);
    }

    public function getInit()
    {
        $this->__load();
        return parent::getInit();
    }

    public function setAtt($att)
    {
        $this->__load();
        return parent::setAtt($att);
    }

    public function getAtt()
    {
        $this->__load();
        return parent::getAtt();
    }

    public function setDef($def)
    {
        $this->__load();
        return parent::setDef($def);
    }

    public function getDef()
    {
        $this->__load();
        return parent::getDef();
    }

    public function setProtec($protec)
    {
        $this->__load();
        return parent::setProtec($protec);
    }

    public function getProtec()
    {
        $this->__load();
        return parent::getProtec();
    }

    public function setEnc($enc)
    {
        $this->__load();
        return parent::setEnc($enc);
    }

    public function getEnc()
    {
        $this->__load();
        return parent::getEnc();
    }

    public function setFort($fort)
    {
        $this->__load();
        return parent::setFort($fort);
    }

    public function getFort()
    {
        $this->__load();
        return parent::getFort();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nom', 'init', 'att', 'def', 'protec', 'enc', 'fort');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}