guildes:
    resource: "@GuildesBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

index:
    resource: "@IndexBundle/Resources/config/routing.yml"
    prefix:   /

elric:
    resource: "@ElricBundle/Resources/config/routing.yml"
    prefix:   /