<?php

namespace GuildesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SortilegeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortilegeRepository extends EntityRepository
{
}
