<?php

namespace JdrCorp\ElricBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersoRepository extends EntityRepository
{
}
