<?php

namespace ElricBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersoRepository extends EntityRepository {
    
}
