Elric_home:
    path:     /
    defaults: { _controller: JdrCorpElricBundle:Elric:index }
Elric:
    path:     /elric
    defaults: { _controller: JdrCorpElricBundle:Elric:index }
Metier_Comp:
    path:     /metierComp/{id}
    defaults: { _controller: JdrCorpElricBundle:Elric:getCompMetier }
