Elric:
    path:     /jdrcorp/elric
    defaults: { _controller: JdrCorpElricBundle:Elric:index }
Elric_Metier_Comp:
    path:     /jdrcorp/elric/metierComp/{id}
    defaults: { _controller: JdrCorpElricBundle:Elric:getCompMetier }
    requirements:
        page:  \d+
        _method:  POST
Elric_Create:
    path:     /jdrcorp/elric/create
    defaults: { _controller: JdrCorpElricBundle:Elric:create }
    requirements:
        _method:  POST  
Elric_review:
    path:     /jdrcorp/elric/review/{id}/{format}
    defaults: { _controller: JdrCorpElricBundle:Elric:review }
    requirements:
        page:  \d+
        _method:  POST
