Elric:
    path:     /elric
    defaults: { _controller: JdrCorpElricBundle:Elric:index }
Elric_Metier_Comp:
    path:     /elric/metierComp/{id}
    defaults: { _controller: JdrCorpElricBundle:Elric:getCompMetier }
    requirements:
        page:  \d+
        _method:  POST
Elric_Create:
    path:     /elric/create
    defaults: { _controller: JdrCorpElricBundle:Elric:create }
    requirements:
        _method:  POST  
Elric_review:
    path:     /elric/review/{id}/{format}
    defaults: { _controller: JdrCorpElricBundle:Elric:review }
    requirements:
        page:  \d+
        _method:  POST
Elric_delete_fiche:
    path:     /elric/delete/{id}
    defaults: { _controller: JdrCorpElricBundle:Elric:delete }
    requirements:
        page:  \d+
        _method:  POST
