Guildes:
    pattern:  /jdrcorp/guildes
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:index }
Guildes_duplicate:
    pattern:  /jdrcorp/guildes/
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:index }
Guildes_duplicate_2:
    pattern:  /jdrcorp/guildes/index
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:index }
Guildes_links:
    pattern:  /jdrcorp/guildes/links/{type}/{id}
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:links }
    requirements:
        _method:  POST
