Guildes:
    pattern:  /jdrcorp/guildes
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:index }
Guildes_duplicate:
    pattern:  /jdrcorp/guildes/
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:index }
Guildes_duplicate_2:
    pattern:  /jdrcorp/guildes/index
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:index }
Guildes_comp:
    pattern:  /jdrcorp/guildes/comp
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:comp }
Guildes_links:
    pattern:  /jdrcorp/guildes/links/{type}/{id}
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:links }
    requirements:
        _method:  POST
Guildes_dice:
    pattern:  /jdrcorp/guildes/dice
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:dice }
Guildes_cdb:
    pattern:  /jdrcorp/guildes/cdb
    defaults: { _controller: JdrCorpGuildesBundle:CDB:cdb }    