Guildes:
    pattern:  /guildes
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:index }
Guildes_duplicate:
    pattern:  /guildes/
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:index }
Guildes_duplicate_2:
    pattern:  /guildes/index
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:index }
Guildes_comp:
    pattern:  /guildes/comp
    defaults: { _controller: JdrCorpGuildesBundle:Comp:comp }
Guildes_links:
    pattern:  /guildes/links/{type}/{id}
    defaults: { _controller: JdrCorpGuildesBundle:Comp:links }
    requirements:
        _method:  POST
Guildes_artefacts:
    pattern:  /guildes/artefacts
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:artefacts } 
Guildes_dice:
    pattern:  /guildes/dice
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:dice }
Guildes_cdb:
    pattern:  /guildes/cdb
    defaults: { _controller: JdrCorpGuildesBundle:CDB:cdb }    
Guildes_loom:
    pattern:  /guildes/loom
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:loom }    
Guildes_armes:
    pattern:  /guildes/armes
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:armes }   
Guildes_equipement:
    pattern:  /guildes/equipement
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:equipement }    
Guildes_machinations:
    pattern:  /guildes/machinations
    defaults: { _controller: JdrCorpGuildesBundle:Guildes:machination } 