parameters:
#    jdr_corp_guildes.example.class: JdrCorp\GuildesBundle\Example

services:
#    jdr_corp_guildes.example:
#        class: %jdr_corp_guildes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
