<?php

namespace JdrCorp\GuildesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MachiNiveauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MachiNiveauRepository extends EntityRepository
{
}
