<?php

namespace Proxies\__CG__\JdrCorp\ElricBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Arme extends \JdrCorp\ElricBundle\Entity\Arme implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'id', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'nom', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'base', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'degats', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'mains', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'structure', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'for_dex', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'type', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'prix', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'total');
        }

        return array('__isInitialized__', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'id', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'nom', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'base', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'degats', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'mains', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'structure', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'for_dex', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'type', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'prix', '' . "\0" . 'JdrCorp\\ElricBundle\\Entity\\Arme' . "\0" . 'total');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Arme $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setBase($base)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBase', array($base));

        return parent::setBase($base);
    }

    /**
     * {@inheritDoc}
     */
    public function getBase()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBase', array());

        return parent::getBase();
    }

    /**
     * {@inheritDoc}
     */
    public function setDegats($degats)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDegats', array($degats));

        return parent::setDegats($degats);
    }

    /**
     * {@inheritDoc}
     */
    public function getDegats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDegats', array());

        return parent::getDegats();
    }

    /**
     * {@inheritDoc}
     */
    public function setMains($mains)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMains', array($mains));

        return parent::setMains($mains);
    }

    /**
     * {@inheritDoc}
     */
    public function getMains()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMains', array());

        return parent::getMains();
    }

    /**
     * {@inheritDoc}
     */
    public function setStructure($structure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStructure', array($structure));

        return parent::setStructure($structure);
    }

    /**
     * {@inheritDoc}
     */
    public function getStructure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructure', array());

        return parent::getStructure();
    }

    /**
     * {@inheritDoc}
     */
    public function setForDex($for_dex)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setForDex', array($for_dex));

        return parent::setForDex($for_dex);
    }

    /**
     * {@inheritDoc}
     */
    public function getForDex()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForDex', array());

        return parent::getForDex();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', array($prix));

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', array());

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', array($total));

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', array());

        return parent::getTotal();
    }

}
