jdr_corp_index_homepage:
    pattern:  /jdrcorp/
    defaults: { _controller: JdrCorpIndexBundle:Index:index }    
jdr_corp_index_homepage_duplicate:
    pattern:  /jdrcorp/index
    defaults: { _controller: JdrCorpIndexBundle:Index:index }    
profile:
    pattern:  /jdrcorp/profile
    defaults: { _controller: JdrCorpIndexBundle:Index:profile }    