parameters:
#    jdr_corp_index.example.class: JdrCorp\IndexBundle\Example

services:
#    jdr_corp_index.example:
#        class: %jdr_corp_index.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
